/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        // Stitch Palette A (landing)
        background: '#06080f',
        surface: '#06080f',
        'surface-tint': '#7FB4CA',
        'surface-container-lowest': '#0c0e15',
        'surface-container-low': '#191b23',
        'surface-container': '#1d1f27',
        'surface-container-high': '#272a32',
        'surface-container-highest': '#32343d',
        'surface-variant': '#32343d',
        'surface-dim': '#11131b',
        'surface-bright': '#373941',
        primary: '#7FB4CA',
        'primary-container': '#7FB4CA',
        'primary-fixed': '#b9eaff',
        'primary-fixed-dim': '#7FB4CA',
        'on-primary': '#003544',
        'on-primary-container': '#004659',
        'on-primary-fixed': '#001f29',
        'on-primary-fixed-variant': '#0d4d60',
        secondary: '#E0C15A',
        'secondary-container': '#806800',
        'secondary-fixed': '#ffe07f',
        'secondary-fixed-dim': '#e3c45d',
        'on-secondary': '#3c2f00',
        'on-secondary-container': '#ffebb2',
        'on-secondary-fixed': '#231b00',
        'on-secondary-fixed-variant': '#564500',
        tertiary: '#bec8d7',
        'tertiary-container': '#a3adbc',
        'tertiary-fixed': '#d9e3f3',
        'tertiary-fixed-dim': '#bdc7d6',
        'on-tertiary': '#27313d',
        'on-tertiary-container': '#37414d',
        'on-tertiary-fixed': '#131c27',
        'on-tertiary-fixed-variant': '#3e4854',
        outline: '#8892A0',
        'outline-variant': '#1a1f2e',
        'on-surface': '#e1e2ed',
        'on-surface-variant': '#8892A0',
        'on-background': '#F3F6F9',
        'inverse-surface': '#e1e2ed',
        'inverse-on-surface': '#2e3038',
        'inverse-primary': '#2e6579',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'window-control-red': '#ef4444',
        'window-control-amber': '#f59e0b',
        'window-control-green': '#22c55e',

        // Stitch Palette B (other pages)
        'background-alt': '#11131b',
        'surface-alt': '#11131b',
        'surface-tint-alt': '#99cee5',
        'primary-alt': '#9ad0e6',
        'primary-fixed-dim-alt': '#99cee5',
        'secondary-alt': '#e3c45d',
        'outline-alt': '#8a9296',
        'outline-variant-alt': '#40484c',
        'on-surface-variant-alt': '#c0c8cc',
        'on-background-alt': '#e1e2ed',
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '4px',
        xl: '4px',
        brutal: '0px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['monospace'],
      },
    },
  },
};
